<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageId>SvgPath</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Units.fs" />
    <Compile Include="Trig.fs" />
    <Compile Include="Point.fs" />
    <Compile Include="Root.fs" />
  </ItemGroup>
</Project>
