<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageId>SvgPath</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Units.fs" />
    <Compile Include="Format.fs" />
    <Compile Include="Trig.fs" />
    <Compile Include="Point.fs" />
    <Compile Include="Affine.fs" />
    <Compile Include="Ellipse.fs" />
    <Compile Include="Root.fs" />
    <Compile Include="Bezier.fs" />
    <Compile Include="Segment.fs" />
    <Compile Include="Curvature.fs" />
    <Compile Include="SmallestEnclosingCircle.fs" />
    <Compile Include="Area.fs" />
    <Compile Include="BasicShapes.fs" />
    <Compile Include="OverlapDetection.fs" />
    <Compile Include="Overlaps.fs" />
    <Compile Include="Intersections.fs" />
    <Compile Include="Encounters.fs" />
    <Compile Include="Cut.fs" />
    <Compile Include="Transform.fs" />
    <Compile Include="TransformSerialize.fs" />
    <Compile Include="ConvexHull.fs" />
    <Compile Include="Degeneracy.fs" />
    <Compile Include="WindingField.fs" />
    <Compile Include="Clip.fs" />
    <Compile Include="Congruency.fs" />
    <Compile Include="Effects.fs" />
  </ItemGroup>
</Project>
