#!/usr/bin/env python3
"""Generate the F# counterpart of svg_path's Bezier bounding-box fixtures."""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
GLEAM_GENERATOR = ROOT.parent / "svg_path" / "scripts" / "generate_bezier_bbox_fixtures.py"
OUTPUT = ROOT / "tests" / "SvgPath.Tests" / "BezierBoundingBoxFixtures.fs"


def load_source_generator():
    spec = importlib.util.spec_from_file_location("gleam_bezier_bbox_fixtures", GLEAM_GENERATOR)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def number(value: float) -> str:
    text = f"{value:.6f}".rstrip("0").rstrip(".")
    if text == "-0":
        text = "0"
    if "." not in text:
        text += ".0"
    return text


def point(value) -> str:
    return f"point {number(value.x)} {number(value.y)}"


def curve(case) -> str:
    arguments = ", ".join(point(value) for value in case.points)
    constructor = {
        "linear": "LinearBezierData",
        "quadratic": "QuadraticBezierData",
        "cubic": "CubicBezierData",
    }[case.kind]
    return f"{constructor}({arguments})"


def render() -> str:
    source = load_source_generator()
    cases = [*source.HAND_CRAFTED_CASES, *source.generated_cases()]
    rows = []
    for case in cases:
        minimum, maximum = source.dense_bbox(case)
        rows.append(f"        {curve(case)}, {point(minimum)}, {point(maximum)}")
    return (
        "// This file is machine-generated by scripts/generate_bezier_bbox_fixtures.py.\n"
        f"// Oracle boxes use {source.SAMPLES} direct Bernstein samples.\n\n"
        "module SvgPath.Tests.BezierBoundingBoxFixtures\n\n"
        "open SvgPath\n\n"
        "let private point x y = Point.create (Length.fromFloat x) (Length.fromFloat y)\n\n"
        "let fixtures =\n"
        "    [\n"
        + "\n".join(rows)
        + "\n    ]\n"
    )


if __name__ == "__main__":
    OUTPUT.write_text(render())
