// This file is machine-generated by scripts/generate_bezier_bbox_fixtures.py.
// Oracle boxes use 200000 direct Bernstein samples.

module SvgPath.Tests.BezierBoundingBoxFixtures

open SvgPath

let private point x y = Point.create (Length.fromFloat x) (Length.fromFloat y)

let fixtures =
    [
        LinearBezierData(point 1.0 2.0, point 5.0 -3.0), point 1.0 -3.0, point 5.0 2.0
        QuadraticBezierData(point 0.0 0.0, point 10.0 10.0, point 20.0 0.0), point 0.0 0.0, point 20.0 5.0
        QuadraticBezierData(point 0.0 0.0, point 10.0 2.0, point 0.0 4.0), point 0.0 0.0, point 5.0 4.0
        QuadraticBezierData(point -3.0 5.0, point 12.0 -8.0, point 6.0 7.0), point -3.0 -1.035714, point 7.714286 7.0
        CubicBezierData(point 0.0 0.0, point 0.0 30.0, point 30.0 30.0, point 30.0 0.0), point 0.0 0.0, point 30.0 22.5
        CubicBezierData(point 0.0 0.0, point 20.0 40.0, point -10.0 -30.0, point 30.0 10.0), point 0.0 -2.833495, point 30.0 12.833495
        CubicBezierData(point 5.0 1.0, point 40.0 20.0, point -30.0 25.0, point 10.0 -15.0), point -2.766373 -15.0, point 15.151446 15.320527
        LinearBezierData(point 13.902 -26.073, point 22.511 3.074), point 13.902 -26.073, point 22.511 3.074
        QuadraticBezierData(point -9.881 -8.999, point 41.606 -35.489, point 1.635 -41.056), point -9.881 -41.056, point 19.104011 -8.999
        CubicBezierData(point 1.781 44.346, point 32.548 -3.012, point 33.131 24.681, point 33.597 -15.639), point 1.781 -15.639, point 33.597 44.346
        LinearBezierData(point -19.667 6.308, point -10.455 -41.28), point -19.667 -41.28, point -10.455 6.308
        QuadraticBezierData(point 17.229 -34.944, point -22.683 48.946, point -47.651 -19.81), point -47.651 -34.944, point 17.229 11.159613
        CubicBezierData(point 37.489 -18.376, point 11.484 31.46, point 20.196 7.446, point -3.508 -44.881), point -3.508 -44.881, point 37.489 8.945008
        LinearBezierData(point -5.929 -23.771, point 44.881 0.259), point -5.929 -23.771, point 44.881 0.259
        QuadraticBezierData(point -27.537 -27.63, point 35.124 -45.246, point -15.156 41.127), point -27.537 -30.614195, point 7.228062 41.127
        CubicBezierData(point 18.034 -15.988, point 23.696 48.264, point 11.83 28.003, point 46.037 -42.899), point 18.034 -42.899, point 46.037 22.76097
        LinearBezierData(point -42.083 -38.856, point 33.777 48.659), point -42.083 -38.856, point 33.777 48.659
        QuadraticBezierData(point -12.229 37.966, point -36.77 -15.015, point -7.856 13.539), point -23.495686 3.539234, point -7.856 37.966
        CubicBezierData(point -39.711 18.094, point 18.116 -17.726, point 31.979 -24.604, point -7.691 -42.405), point -39.711 -42.405, point 14.869396 18.094
        LinearBezierData(point -25.438 23.246, point -8.556 -34.511), point -25.438 -34.511, point -8.556 23.246
        QuadraticBezierData(point 7.887 -32.575, point 37.41 47.678, point 43.067 -23.545), point 7.887 -32.575, point 43.067 9.943577
        CubicBezierData(point 20.532 -27.827, point -39.662 12.817, point -37.388 -40.605, point -9.348 21.316), point -28.323965 -27.827, point 20.532 21.316
        LinearBezierData(point -9.755 39.281, point 20.735 1.692), point -9.755 1.692, point 20.735 39.281
        QuadraticBezierData(point -47.82 -0.857, point -3.932 -47.488, point 12.65 34.428), point -47.82 -17.772604, point 12.65 34.428
        CubicBezierData(point -40.639 46.18, point 41.012 -8.934, point -28.815 7.67, point 28.414 -47.318), point -40.639 -47.318, point 28.414 46.18
        LinearBezierData(point 45.804 -33.412, point 25.826 6.117), point 25.826 -33.412, point 45.804 6.117
        QuadraticBezierData(point 27.93 8.194, point 35.971 16.204, point -1.19 21.713), point -1.19 8.194, point 29.360416 21.713
        CubicBezierData(point -45.508 45.561, point -49.091 -15.734, point -18.926 -0.108, point -28.74 -4.529), point -45.80542 -4.529, point -26.766472 45.561
        LinearBezierData(point -22.93 -4.838, point -20.834 -11.159), point -22.93 -11.159, point -20.834 -4.838
        QuadraticBezierData(point -35.855 17.794, point 24.669 -0.311, point 20.783 -42.174), point -35.855 -42.174, point 21.017451 17.794
        CubicBezierData(point -11.099 -14.218, point 21.965 2.363, point -25.698 -16.084, point -10.643 -44.471), point -13.673543 -44.471, point 0.851364 -7.947449
        LinearBezierData(point -22.031 -28.986, point -41.348 -44.032), point -41.348 -44.032, point -22.031 -28.986
        QuadraticBezierData(point 33.823 23.504, point -46.806 -6.666, point 44.155 47.566), point -4.064031 12.719553, point 44.155 47.566
        CubicBezierData(point -31.862 1.502, point -18.999 -35.332, point 4.278 -33.361, point 5.66 2.228), point -31.862 -25.303037, point 5.66 2.228
        LinearBezierData(point -12.674 5.692, point -19.717 49.937), point -19.717 5.692, point -12.674 49.937
        QuadraticBezierData(point -17.145 3.437, point 42.631 -12.508, point -15.669 9.105), point -17.145 -3.332344, point 13.116613 9.105
        CubicBezierData(point -38.693 -19.224, point -45.353 35.701, point 7.395 43.23, point -39.43 -38.5), point -39.43 -38.5, point -19.851417 22.478712
        LinearBezierData(point 11.02 -38.578, point 30.942 -27.484), point 11.02 -38.578, point 30.942 -27.484
        QuadraticBezierData(point 47.831 -6.904, point 24.931 7.45, point 47.392 12.105), point 36.270188 -6.904, point 47.831 12.105
        CubicBezierData(point -35.465 -31.683, point 27.942 6.929, point -1.109 -44.967, point 16.117 -21.609), point -35.465 -31.683, point 16.117 -16.8829
        LinearBezierData(point 21.181 -48.634, point 19.355 -29.965), point 19.355 -48.634, point 21.181 -29.965
        QuadraticBezierData(point -10.259 -40.506, point -42.84 27.666, point 49.268 0.12), point -18.772354 -40.506, point 49.268 8.047267
        CubicBezierData(point -14.172 -26.023, point 46.567 4.624, point -45.889 -14.814, point 10.689 16.358), point -14.172 -26.023, point 10.689 16.358
        LinearBezierData(point -47.626 35.479, point 16.409 27.118), point -47.626 27.118, point 16.409 35.479
        QuadraticBezierData(point -11.526 0.103, point 4.381 -20.367, point 31.569 4.173), point -11.526 -9.206507, point 31.569 4.173
        CubicBezierData(point -37.829 -37.667, point 35.944 -25.246, point -44.919 -8.828, point 42.84 37.743), point -37.829 -37.667, point 42.84 37.743
        LinearBezierData(point -40.827 -32.598, point -30.439 25.448), point -40.827 -32.598, point -30.439 25.448
        QuadraticBezierData(point -40.735 3.398, point 23.691 28.729, point -5.319 -27.298), point -40.735 -27.298, point 3.688022 11.284865
        CubicBezierData(point 23.849 -24.804, point 45.165 -15.149, point 44.176 -30.368, point 19.287 -26.182), point 19.287 -26.928661, point 38.957439 -21.534754
        LinearBezierData(point 29.129 -0.313, point -44.404 41.324), point -44.404 -0.313, point 29.129 41.324
        QuadraticBezierData(point 14.987 -42.831, point -47.579 -30.734, point 22.316 47.929), point -14.565127 -42.831, point 22.316 47.929
        CubicBezierData(point -4.326 3.177, point 25.927 27.592, point -37.388 -41.196, point 46.544 44.536), point -4.326 -0.069621, point 46.544 44.536
        LinearBezierData(point -24.759 3.982, point -40.271 -40.737), point -40.271 -40.737, point -24.759 3.982
        QuadraticBezierData(point 32.32 -12.357, point -40.476 -46.069, point -4.678 -24.366), point -16.478807 -32.865868, point 32.32 -12.357
        CubicBezierData(point 38.805 23.345, point -31.91 -12.319, point 15.483 13.355, point 41.318 -40.983), point 1.675958 -40.983, point 41.318 23.345
        LinearBezierData(point 48.277 46.83, point -45.362 -37.268), point -45.362 -37.268, point 48.277 46.83
        QuadraticBezierData(point -11.731 -1.518, point -3.763 38.698, point 11.161 -1.701), point -11.731 -1.701, point 11.161 18.544354
        CubicBezierData(point -29.556 3.181, point 34.295 -36.511, point -45.655 17.969, point -7.527 21.173), point -29.556 -11.241187, point -3.83053 21.173
        LinearBezierData(point 24.332 20.952, point 13.882 21.755), point 13.882 20.952, point 24.332 21.755
        QuadraticBezierData(point 31.639 -28.575, point -32.044 37.572, point -21.175 -20.64), point -22.759601 -28.575, point 31.639 6.608828
        CubicBezierData(point 11.486 -45.925, point 30.251 44.594, point 42.944 43.899, point 3.659 -25.67), point 3.659 -45.925, point 29.379077 24.460194
        LinearBezierData(point -40.098 14.027, point -31.408 2.557), point -40.098 2.557, point -31.408 14.027
        QuadraticBezierData(point -22.659 27.255, point 34.346 -39.383, point 43.906 -26.509), point -22.659 -28.593464, point 43.906 27.255
        CubicBezierData(point 12.929 -45.732, point 23.08 -37.912, point 32.891 10.738, point -22.144 -11.138), point -22.144 -45.732, point 20.824259 -5.530526
        LinearBezierData(point -15.724 -10.737, point 43.266 -46.152), point -15.724 -46.152, point 43.266 -10.737
        QuadraticBezierData(point -46.128 0.895, point -43.673 -38.599, point 5.603 -23.693), point -46.128 -27.777354, point 5.603 0.895
        CubicBezierData(point 40.327 0.754, point 20.045 5.429, point -41.614 20.612, point -26.062 -30.201), point -28.549241 -30.201, point 40.327 6.537307
        LinearBezierData(point 7.07 -9.675, point -14.268 -14.157), point -14.268 -14.157, point 7.07 -9.675
        QuadraticBezierData(point -35.239 -21.611, point -25.764 -2.368, point -12.326 40.536), point -35.239 -21.611, point -12.326 40.536
        CubicBezierData(point -32.481 -30.508, point 21.39 -1.593, point 40.87 45.793, point 32.332 33.404), point -32.481 -30.508, point 34.261379 35.427187
        LinearBezierData(point 22.514 41.333, point -35.26 -15.424), point -35.26 -15.424, point 22.514 41.333
        QuadraticBezierData(point 24.261 0.008, point 39.496 0.065, point 12.369 26.658), point 12.369 0.008, point 29.74009 26.658
        CubicBezierData(point 23.429 7.061, point -33.157 -27.631, point 35.588 -37.732, point 23.97 41.59), point 0.787114 -18.930868, point 25.320734 41.59
        LinearBezierData(point -43.815 3.226, point -10.812 40.568), point -43.815 3.226, point -10.812 40.568
        QuadraticBezierData(point -23.992 14.674, point -9.955 17.808, point -44.983 -27.452), point -44.983 -27.452, point -19.976156 14.876958
        CubicBezierData(point -10.637 16.087, point -45.194 15.701, point 49.284 9.28, point -37.185 -43.554), point -37.185 -43.554, point 0.449908 16.087
        LinearBezierData(point -47.029 -13.562, point 14.996 -48.574), point -47.029 -48.574, point 14.996 -13.562
        QuadraticBezierData(point 45.998 19.683, point 34.386 27.538, point 42.003 -12.44), point 38.985751 -12.44, point 45.998 20.972926
        CubicBezierData(point 40.33 17.306, point -22.885 -19.372, point 42.984 -2.57, point 46.435 -15.466), point 13.022574 -15.466, point 46.435 17.306
        LinearBezierData(point 8.501 0.752, point -7.433 -32.941), point -7.433 -32.941, point 8.501 0.752
        QuadraticBezierData(point 33.958 46.024, point 40.22 0.624, point -21.955 0.193), point -21.955 0.193, point 34.530974 46.024
        CubicBezierData(point -23.268 -28.324, point -24.408 -49.656, point 43.215 8.243, point 43.33 -23.422), point -23.282253 -33.171093, point 43.33 -13.72785
        LinearBezierData(point 38.944 29.822, point 18.61 -45.682), point 18.61 -45.682, point 38.944 29.822
        QuadraticBezierData(point -31.478 -2.638, point 17.894 -36.476, point -40.527 -48.069), point -40.527 -48.069, point -8.864339 -2.638
        CubicBezierData(point -18.425 49.27, point -16.249 35.774, point -14.619 -5.967, point -16.123 -49.171), point -18.425 -49.171, point -15.539226 49.27
        LinearBezierData(point -23.544 12.395, point -45.488 -21.02), point -45.488 -21.02, point -23.544 12.395
        QuadraticBezierData(point -38.021 -44.126, point -4.157 -12.507, point 14.548 -5.728), point -38.021 -44.126, point 14.548 -5.728
        CubicBezierData(point 2.924 -22.125, point -46.469 44.415, point -24.665 -37.482, point 40.311 34.588), point -24.084822 -22.125, point 40.311 34.588
        LinearBezierData(point -3.317 12.882, point -22.522 -23.494), point -22.522 -23.494, point -3.317 12.882
        QuadraticBezierData(point 48.23 28.31, point 30.074 39.266, point 21.919 31.918), point 21.919 28.31, point 48.23 34.867798
        CubicBezierData(point 6.519 25.133, point 17.434 -40.726, point -39.063 -18.306, point 6.794 -32.935), point -11.426513 -32.935, point 7.952048 25.133
        LinearBezierData(point -27.856 48.108, point 12.013 35.335), point -27.856 35.335, point 12.013 48.108
        QuadraticBezierData(point 23.235 -17.305, point -45.912 -11.661, point 18.286 -49.455), point -12.62167 -49.455, point 23.235 -16.571662
        CubicBezierData(point 5.371 42.23, point -33.834 -49.494, point -13.737 36.917, point -34.279 -40.719), point -34.279 -40.719, point 5.371 42.23
        LinearBezierData(point 39.441 -34.9, point -47.548 26.156), point -47.548 -34.9, point 39.441 26.156
        QuadraticBezierData(point 6.599 -23.987, point -8.319 -8.024, point -13.236 44.581), point -13.236 -23.987, point 6.599 44.581
        CubicBezierData(point 48.118 46.008, point -46.033 -42.791, point -26.79 -13.049, point 49.058 -17.234), point -15.384807 -18.799584, point 49.058 46.008
        LinearBezierData(point 23.851 29.4, point 46.324 -42.648), point 23.851 -42.648, point 46.324 29.4
        QuadraticBezierData(point 4.722 -36.059, point -2.87 36.583, point 21.573 -43.729), point 2.922766 -43.729, point 21.573 -1.559345
        CubicBezierData(point 32.715 -17.799, point 36.521 -44.674, point -0.446 -41.542, point 20.183 49.218), point 13.883318 -32.540887, point 32.992412 49.218
        LinearBezierData(point -29.189 -17.485, point -23.377 -19.9), point -29.189 -19.9, point -23.377 -17.485
        QuadraticBezierData(point -38.222 14.998, point 42.643 -42.833, point 0.463 -36.501), point -38.222 -37.125881, point 14.922364 14.998
        CubicBezierData(point 43.447 32.578, point 47.544 -33.5, point 22.431 9.615, point 32.44 -44.581), point 30.064258 -44.581, point 43.903231 32.578
        LinearBezierData(point 48.112 -35.009, point -13.56 -12.056), point -13.56 -35.009, point 48.112 -12.056
        QuadraticBezierData(point -23.337 12.499, point -2.214 8.699, point -39.188 -11.401), point -39.188 -11.401, point -15.657066 12.499
        CubicBezierData(point -27.338 -23.07, point -41.659 11.365, point 25.634 -14.41, point -24.033 -17.144), point -29.384457 -23.07, point -5.461776 -5.316023
        LinearBezierData(point -20.031 1.35, point -1.204 28.656), point -20.031 1.35, point -1.204 28.656
        QuadraticBezierData(point -45.136 36.158, point -48.061 11.6, point -21.072 38.657), point -45.422007 24.473502, point -21.072 38.657
        CubicBezierData(point -37.151 17.67, point 19.744 6.902, point 28.748 29.581, point 24.567 -48.955), point -37.151 -48.955, point 25.454031 17.67
        LinearBezierData(point 13.671 29.796, point -35.807 41.927), point -35.807 29.796, point 13.671 41.927
        QuadraticBezierData(point -19.633 5.663, point 41.707 33.203, point 41.863 -43.011), point -19.633 -43.011, point 41.863 12.973095
        CubicBezierData(point 14.83 -35.952, point -44.68 -15.241, point 10.081 45.285, point 39.768 2.878), point -11.766104 -35.952, point 39.768 17.613961
        LinearBezierData(point -9.622 9.889, point -6.838 12.286), point -9.622 9.889, point -6.838 12.286
        QuadraticBezierData(point 6.255 -27.62, point 22.28 -9.384, point -34.387 30.059), point -34.387 -27.62, point 9.787722 30.059
        CubicBezierData(point 44.34 41.9, point 41.95 30.627, point 19.348 -26.249, point 22.763 2.236), point 22.412443 -5.661631, point 44.34 41.9
        LinearBezierData(point -39.751 28.147, point -30.701 45.731), point -39.751 28.147, point -30.701 45.731
        QuadraticBezierData(point -46.318 -28.644, point -15.417 29.049, point -39.542 -9.747), point -46.318 -28.644, point -28.964898 5.851976
        CubicBezierData(point 11.141 -8.04, point 42.474 -23.743, point -0.236 -11.985, point -26.775 33.189), point -26.775 -14.641488, point 22.167318 33.189
        LinearBezierData(point -14.06 -27.217, point 25.84 -21.318), point -14.06 -27.217, point 25.84 -21.318
        QuadraticBezierData(point -47.388 24.473, point 30.531 -30.616, point -6.77 -26.422), point -47.388 -26.718706, point 5.305721 24.473
        CubicBezierData(point -4.631 -5.959, point 19.146 30.195, point -29.051 31.606, point -15.783 -7.24), point -18.137954 -7.24, point 2.067587 21.525521
        LinearBezierData(point 42.685 3.348, point 3.85 48.011), point 3.85 3.348, point 42.685 48.011
        QuadraticBezierData(point 35.09 -17.256, point -24.83 30.398, point 25.66 43.554), point 2.571148 -17.256, point 35.09 43.554
        CubicBezierData(point 20.988 7.481, point -39.498 -5.988, point -49.916 -2.669, point 30.999 45.044), point -27.031985 0.612321, point 30.999 45.044
        LinearBezierData(point 46.615 -13.097, point 42.941 0.252), point 42.941 -13.097, point 46.615 0.252
        QuadraticBezierData(point 8.226 38.952, point 16.794 33.169, point 29.293 24.31), point 8.226 24.31, point 29.293 38.952
        CubicBezierData(point 28.792 41.325, point 11.208 -4.378, point -33.881 -39.219, point -45.65 23.784), point -45.65 -10.443064, point 28.792 41.325
        LinearBezierData(point -20.818 36.543, point 19.32 -25.277), point -20.818 -25.277, point 19.32 36.543
        QuadraticBezierData(point -39.216 0.353, point 37.088 48.006, point 32.332 -0.201), point -39.216 -0.201, point 32.611047 24.0418
        CubicBezierData(point -40.685 -44.137, point -45.914 18.557, point 42.32 -17.611, point 45.641 8.178), point -40.908481 -44.137, point 45.641 8.178
        LinearBezierData(point 40.32 -9.014, point 38.96 27.119), point 38.96 -9.014, point 40.32 27.119
        QuadraticBezierData(point 45.341 12.965, point 1.671 -7.331, point -43.748 39.056), point -43.748 6.787599, point 45.341 39.056
        CubicBezierData(point -21.821 -21.858, point -35.178 -42.759, point -27.407 -0.172, point -9.135 35.17), point -28.537679 -27.387703, point -9.135 35.17
        LinearBezierData(point -20.349 35.55, point -34.704 -3.365), point -34.704 -3.365, point -20.349 35.55
        QuadraticBezierData(point -37.498 -45.805, point -0.781 -6.605, point 9.595 -34.739), point -37.498 -45.805, point 9.595 -22.98384
        CubicBezierData(point 21.404 23.535, point 49.443 27.029, point -16.756 47.061, point 21.79 32.896), point 9.385117 23.535, point 28.549649 37.902521
        LinearBezierData(point 12.183 -16.878, point 30.244 -8.729), point 12.183 -16.878, point 30.244 -8.729
        QuadraticBezierData(point -49.303 26.482, point -36.358 29.148, point -30.041 28.158), point -49.303 26.482, point -30.041 28.42608
        CubicBezierData(point -22.537 1.662, point -36.98 41.01, point 43.952 42.106, point -7.275 41.578), point -24.292605 1.662, point 9.924615 41.654971
        LinearBezierData(point -12.872 39.658, point -11.459 26.978), point -12.872 26.978, point -11.459 39.658
        QuadraticBezierData(point -1.767 27.296, point 41.092 40.329, point 34.774 29.908), point -1.767 27.296, point 35.585703 34.538223
        CubicBezierData(point -12.614 4.558, point 36.563 -10.034, point 49.816 -31.443, point -5.978 -17.941), point -12.614 -22.228317, point 30.417968 4.558
        LinearBezierData(point -7.639 23.237, point -15.164 26.371), point -15.164 23.237, point -7.639 26.371
        QuadraticBezierData(point -2.447 2.488, point 32.834 0.952, point -27.417 -31.516), point -27.417 -31.516, point 10.582655 2.488
        CubicBezierData(point 8.283 -15.415, point -2.277 8.172, point 0.912 -0.195, point -5.076 -0.825), point -5.076 -15.415, point 8.283 1.123946
        LinearBezierData(point 32.494 -24.363, point 46.46 17.469), point 32.494 -24.363, point 46.46 17.469
        QuadraticBezierData(point -33.136 15.268, point -2.15 -1.331, point 7.081 15.37), point -33.136 6.993922, point 7.081 15.37
        CubicBezierData(point -40.789 -48.357, point -13.028 -44.436, point 38.349 -41.03, point 28.551 28.292), point -40.789 -48.357, point 29.775596 28.292
        LinearBezierData(point -45.468 -46.127, point 42.418 24.68), point -45.468 -46.127, point 42.418 24.68
        QuadraticBezierData(point 5.475 -46.488, point -28.069 -25.233, point -24.419 47.094), point -24.777189 -46.488, point 5.475 47.094
        CubicBezierData(point -45.614 36.105, point -2.283 -22.523, point -27.899 11.265, point -18.669 37.429), point -45.614 3.701444, point -18.669 37.429
        LinearBezierData(point 39.74 21.109, point -8.034 -6.729), point -8.034 -6.729, point 39.74 21.109
        QuadraticBezierData(point 20.637 20.229, point -22.224 28.784, point -22.697 -13.885), point -22.697 -13.885, point 20.637 21.657784
        CubicBezierData(point 4.88 31.197, point -28.171 -37.237, point -22.252 38.93, point 22.931 25.809), point -16.120895 2.257436, point 22.931 31.197
        LinearBezierData(point 39.88 20.328, point 22.871 -21.145), point 22.871 -21.145, point 39.88 20.328
        QuadraticBezierData(point -27.241 -32.639, point 7.649 16.747, point -16.027 -8.044), point -27.241 -32.639, point -6.455696 0.241502
        CubicBezierData(point -39.526 -45.99, point 3.748 32.585, point -46.89 -40.022, point -15.809 -37.024), point -39.526 -45.99, point -15.809 -9.319208
    ]
