<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Library</OutputType>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="PointTests.fs" />
    <Compile Include="AffineTests.fs" />
    <Compile Include="EllipseTests.fs" />
    <Compile Include="TrigTests.fs" />
    <Compile Include="RootTests.fs" />
    <Compile Include="BezierTests.fs" />
    <Compile Include="SegmentTests.fs" />
    <Compile Include="CurvatureTests.fs" />
    <Compile Include="SmallestEnclosingCircleTests.fs" />
    <Compile Include="AreaTests.fs" />
    <Compile Include="BasicShapesTests.fs" />
    <Compile Include="OverlapDetectionTests.fs" />
    <Compile Include="OverlapsTests.fs" />
    <Compile Include="IntersectionsTests.fs" />
    <Compile Include="TransformTests.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/SvgPath/SvgPath.fsproj" />
  </ItemGroup>
</Project>
